export const dockApps = [
  { id: "finder", name: "Portfolio", icon: "finder.png", canOpen: true },
  { id: "launchpad", name: "Launchpad", icon: "Launchpad.png", canOpen: true },
  { id: "safari", name: "Safari", icon: "safari.png", canOpen: true },
  { id: "photos", name: "Gallery", icon: "photos.png", canOpen: true },
  { id: "contact", name: "Contact", icon: "contact.png", canOpen: true },
  { id: "terminal", name: "Terminal", icon: "terminal.png", canOpen: true },
  { id: "settings", name: "System Settings", icon: "settings.png", canOpen: true },
  { id: "calculator", name: "Calculator", icon: "calculator.png", canOpen: true },
  { id: "notes", name: "Notes", icon: "notes.png", canOpen: true },
  { id: "call", name: "FaceTime", icon: "call.png", canOpen: true },
  { id: "messages", name: "Messages", icon: "message.png", canOpen: true },
  { id: "appletv", name: "Apple TV", icon: "appletv.png", canOpen: true },
  { id: "appstore", name: "App Store", icon: "appstore.png", canOpen: true },
  { id: "calendar", name: "Calendar", icon: "calendar.png", canOpen: true },
  { id: "weather", name: "Weather", icon: "weather.png", canOpen: true },
  { id: "vscode", name: "VS Code", icon: "vscode.png", canOpen: true },
  { id: "postman", name: "Postman", icon: "postman.png", canOpen: true },
  { id: "map", name: "Maps", icon: "map.png", canOpen: true },
  { id: "font", name: "Font Book", icon: "font.png", canOpen: true },
  { id: "telegram", name: "Telegram", icon: "telegram.png", canOpen: true },
  { id: "music", name: "Music", icon: "music.png", canOpen: true },
  { id: "folder", name: "Projects Folder", icon: "folder.png", canOpen: true },
  { id: "trash", name: "Trash", icon: "trash.png", canOpen: true },
];
