import {
  PROJECT_1_URL,
  PROJECT_1_GITHUB,
  PROJECT_2_URL,
  PROJECT_2_GITHUB,
  PROJECT_3_URL,
  PROJECT_3_GITHUB,
  PROJECT_4_URL,
  PROJECT_4_GITHUB,
} from "./env";

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/system/icons/ui/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "NewTube",
      icon: "/system/icons/files/folder.webp",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-6",
      children: [
        {
          id: 1,
          name: "NewTube Project.txt",
          icon: "/system/icons/files/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This platform is a modern video streaming application built for performance, scalability, and user engagement. It features an advanced video player with quality controls, playback speed, picture-in-picture, and keyboard shortcuts for a smooth experience. Powered by Mux, videos are processed, optimized, and delivered globally via a fast CDN.",
            "It includes AI-powered tools for thumbnail generation, title suggestions, and description optimization, helping creators boost discoverability. The Creator Studio provides analytics, engagement metrics, and growth tracking. ",
            "Built with Next.js, Tailwind CSS, tRPC, and PostgreSQL, it ensures a fast, responsive, and scalable architecture across all devices.",
          ],
        },
        {
          id: 2,
          name: "newtube.com",
          icon: "/apps/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_1_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "newtube.png",
          icon: "/system/icons/files/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/desktop/newtube.webp",
          imageMobUrl: "/projects/mobile/newtube-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/brands/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_1_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 6,
      name: "Coursenva",
      icon: "/system/icons/files/folder.webp",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-6",
      children: [
        {
          id: 1,
          name: "Coursenva Project.txt",
          icon: "/system/icons/files/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "Coursenva is an AI-powered course finder and custom roadmap generator designed to discover high-quality free online courses from Coursera, edX, MIT OCW, YouTube, and Khan Academy.",
            "Using search grounding and intelligent course curation, it allows learners to build personalized career roadmaps and chat with an AI learning assistant to master new skills effortlessly.",
            "Built with Next.js, Tailwind CSS, and AI search integration, ensuring a fast, clean, and highly responsive learning space for students and developers worldwide.",
          ],
        },
        {
          id: 2,
          name: "coursenva.com",
          icon: "/apps/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_2_URL,
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "coursenva.png",
          icon: "/system/icons/files/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/projects/desktop/coursenva.webp",
          imageMobUrl: "/projects/mobile/coursenva-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/brands/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_2_GITHUB,
          position: "top-60 left-5",
        },
      ],
    },
    {
      id: 7,
      name: "Resume Ats Scanner",
      icon: "/system/icons/files/folder.webp",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[35vh] left-6",
      children: [
        {
          id: 1,
          name: "Resume Ats Scanner Project.txt",
          icon: "/system/icons/files/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This is an AI-powered resume parsing and analysis platform designed to help job seekers optimize their resumes for Applicant Tracking Systems (ATS).",
            "It extracts key information from uploaded resumes, analyzes them against job descriptions, and provides detailed feedback on keyword optimization, formatting issues, and content improvements.",
            "Built with Groq API, it ensures accurate parsing and intelligent scoring, helping users increase their chances of passing through automated screening processes.",
          ],
        },
        {
          id: 2,
          name: "resumeatsscanner.com",
          icon: "/apps/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_3_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "resumeatsscanner.png",
          icon: "/system/icons/files/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/desktop/resume-ats.webp",
          imageMobUrl: "/projects/mobile/resume-ats-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/brands/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_3_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 8,
      name: "Docs Editor",
      icon: "/system/icons/files/folder.webp",
      kind: "folder",
      position: "top-52 left-5",
      windowPosition: "top-[50vh] left-6",
      children: [
        {
          id: 1,
          name: "Docs Editor Project.txt",
          icon: "/system/icons/files/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This is a powerful, real-time collaborative document editor built to allow multiple users to edit rich-text documents simultaneously with high performance.",
            "Powered by Liveblocks and Yjs CRDT, it features conflict-free editing, live cursor tracking, presence indicators, and inline comment threads. It integrates Tiptap for rich-text formatting, document headers, and image insertion.",
            "Built with Next.js 15, Clerk for secure user authentication, Convex for database storage, and Zustand for state management, ensuring a modern, responsive, and secure experience.",
          ],
        },
        {
          id: 2,
          name: "docs-editor.com",
          icon: "/apps/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_4_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "docs-editor.png",
          icon: "/system/icons/files/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/desktop/docs-editor.webp",
          imageMobUrl: "/projects/mobile/docs-editor-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/brands/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_4_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/system/icons/ui/info.svg",
  kind: "folder",
  children: [
    {
      id: 4,
      name: "about-me.txt",
      icon: "/system/icons/files/txt.webp",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      description: [
        "Hey! I'm Kuldeep 👋, a web developer who enjoys building sleek, interactive websites that actually work well.",
        "I specialize in JavaScript, React, and Next.js—and I love making things feel smooth, fast, and just a little bit delightful.",
        "Outside of dev work, you'll find me tweaking layouts at 2AM, sipping overpriced coffee, or impulse-buying gadgets I absolutely convinced myself I needed 😅",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/system/icons/files/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/system/icons/files/pdf.webp",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/system/icons/dock/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/system/icons/files/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/trash/trash-1.webp",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/system/icons/files/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/trash/trash-2.webp",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};
